name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy via FTP (dist only)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # IP exacta provista por Hostinger en tu captura
          server: 82.180.138.197
          
          # Nombre de usuario completo con el ".cl" al final
          username: u349541296.rollerhanko.cl
          password: ${{ secrets.FTP_PASS }}

          # Protocolo estándar para puerto 21 en Hostinger
          protocol: sftp
          port: 21

          # Carpeta local que genera tu comando "npm run build"
          local-dir: ./dist/
          
          # Carpeta destino del hosting para que tu web sea visible al público
          server-dir: ./public_html/

          dangerous-clean-slate: false
